name = "gwood-dev"
compatibility_date = "2026-02-05"
pages_build_output_dir = "dist"

[vars]
# Add any environment variables here if needed

[[pages_build_config]]
build_command = "npm run build"
destination_dir = "dist"
not_found_handling = "single-page-application"
