name = "gwood-dev"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[assets]
not_found_handling = "single-page-application"

[vars]
# Add any environment variables here if needed

[[pages_build_config]]
build_command = "npm run build"
destination_dir = "dist"
